import { Space, Review, UserProfile } from './types';

export interface CategoryAvatarInfo {
  categoryKey: string;
  categoryLabel: string;
  hostName: string;
  hostRole: string;
  gender: 'male' | 'female';
  avatarUrl: string;
  bio: string;
}

export const CATEGORY_AVATARS: Record<string, CategoryAvatarInfo> = {
  coworking: {
    categoryKey: 'WORK',
    categoryLabel: 'Workspaces & Desks',
    hostName: 'Tunde Adebayo',
    hostRole: 'Workspace Curator',
    gender: 'male',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    bio: 'Curating silent, ergonomic and fiber-connected work hubs across Nigeria.',
  },
  photography: {
    categoryKey: 'CREATE',
    categoryLabel: 'Creative & Photo Studios',
    hostName: 'Chioma Okonkwo',
    hostRole: 'Studio Director',
    gender: 'female',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    bio: 'Visual arts director and daylight studio curator in Yaba & Lekki.',
  },
  meeting: {
    categoryKey: 'MEET',
    categoryLabel: 'Executive Boardrooms',
    hostName: 'Babajide Adeleke',
    hostRole: 'Executive Suites Lead',
    gender: 'male',
    avatarUrl: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    bio: 'Hosting high-stakes boardroom sessions, investor decks, and offsites.',
  },
  podcast: {
    categoryKey: 'RECORD',
    categoryLabel: 'Podcast & Audio/Video',
    hostName: 'Amina Bello',
    hostRole: 'Audio & Broadcast Lead',
    gender: 'female',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80',
    bio: 'Sound engineer managing acoustic broadcast booths and 4K recording suites.',
  },
};

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user_tunde',
    name: 'Tunde Adebayo',
    email: 'tunde@ofis.ng',
    phone: '+234 803 456 7890',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    bio: 'Fintech product lead & remote worker based in Lagos.',
    company: 'PayScale Africa',
    walletBalance: 85000,
    savedSpaces: ['space_1', 'space_3'],
    notificationsEnabled: true,
  },
  {
    id: 'user_chioma',
    name: 'Chioma Okonkwo',
    email: 'chioma@ofis.ng',
    phone: '+234 812 345 6789',
    role: 'host',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    bio: 'Founder at The Hive Ikoyi & creative space curator.',
    company: 'Hive Spaces Lagos',
    walletBalance: 420000,
    savedSpaces: ['space_2'],
    notificationsEnabled: true,
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    spaceId: 'space_1',
    userId: 'user_tunde',
    userName: 'Tunde Adebayo',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    date: '3 days ago',
    comment: 'The power stability is 100% reliable. Had 4 uninterrupted client video calls on their fast wired and wireless internet. Clean ergonomic chairs and great iced coffee downstairs.',
    tags: ['24/7 Power', 'Fast Wifi', 'Ergonomic'],
    verifiedStay: true,
  },
  {
    id: 'rev_2',
    spaceId: 'space_1',
    userId: 'user_funke',
    userName: 'Funke Alabi',
    userAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&auto=format&fit=crop&q=80',
    rating: 4.9,
    date: '1 week ago',
    comment: 'Booked a private phone booth for 3 hours. Seamless instant check-in with the digital pass QR code.',
    tags: ['Quiet', 'Instant Pass'],
    verifiedStay: true,
  },
  {
    id: 'rev_3',
    spaceId: 'space_3',
    userId: 'user_emeka',
    userName: 'Emeka Nwosu',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    date: '2 days ago',
    comment: 'Recorded 2 podcast episodes with the Shure SM7B mics and Rodecaster Pro II. Soundproofing was completely isolated from Victoria Island traffic.',
    tags: ['Acoustic Treatment', 'Pro Microphones', 'Soundproof'],
    verifiedStay: true,
  }
];

export const MOCK_SPACES: Space[] = [
  {
    id: 'space_1',
    title: 'The Foundry Executive Desk & Lounge',
    tagline: 'Premium quiet workspace with redundant solar-generator grid and high-speed fiber.',
    description: 'Located in the heart of Victoria Island, The Foundry offers an elevated sanctuary for founders, executives, and remote creatives. Featuring Herman Miller seating, dual 300Mbps high-speed fiber lines with automated redundancy, and continuous uninterrupted power.',
    category: 'coworking',
    city: 'Lagos',
    neighborhood: 'Victoria Island',
    address: '14 Karimu Kotun St, Victoria Island, Lagos',
    coordinates: { lat: 6.4281, lng: 3.4219 },
    pricePerHour: 3500,
    pricePerDay: 22000,
    currency: 'NGN',
    rating: 4.95,
    reviewsCount: 68,
    capacity: 24,
    images: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '24/7 Solar & Gen Power',
      '300Mbps Fast Fiber Internet',
      'Ergonomic Herman Miller Chairs',
      'Artisanal Coffee & Tea Bar',
      'Acoustic Phone Booths',
      'Secure Onsite Parking',
      'Access Card / QR Digital Pass',
      'Chilled Filtered Water'
    ],
    hostId: 'user_tunde',
    hostName: 'Tunde Adebayo',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '99% • Under 5 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: '24/7 Solar & Inverter',
    internetSpeedMbps: 300,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:00 AM - 10:00 PM',
      saturday: '8:00 AM - 8:00 PM',
      sunday: '10:00 AM - 6:00 PM',
    },
    rules: [
      'Quiet workspace in central zone; use phone booths for voice calls',
      'No hot or pungent food at individual work desks',
      'Digital pass scan required at turnstiles'
    ],
    tags: ['Fast Fiber', 'Solar Backed', 'Victoria Island', 'Instant Book'],
    isVerified: true,
    floorPlanSeats: [
      { id: 'desk-01', label: 'Desk 01 (Window View)', type: 'dedicated_desk', status: 'available', pricePerHour: 3500, x: 20, y: 30 },
      { id: 'desk-02', label: 'Desk 02 (Window View)', type: 'dedicated_desk', status: 'available', pricePerHour: 3500, x: 35, y: 30 },
      { id: 'desk-03', label: 'Desk 03 (Quiet Zone)', type: 'hot_desk', status: 'occupied', pricePerHour: 3500, x: 50, y: 30 },
      { id: 'desk-04', label: 'Desk 04 (Quiet Zone)', type: 'hot_desk', status: 'available', pricePerHour: 3500, x: 65, y: 30 },
      { id: 'booth-01', label: 'Phone Booth A', type: 'booth', status: 'available', pricePerHour: 4500, x: 80, y: 65 },
      { id: 'booth-02', label: 'Phone Booth B', type: 'booth', status: 'reserved', pricePerHour: 4500, x: 80, y: 80 },
    ]
  },
  {
    id: 'space_2',
    title: 'The Glasshouse Boardroom & Strategy Suite',
    tagline: 'High-tech 12-person meeting suite with 4K interactive display and Zoom Rooms integration.',
    description: 'Designed for high-stakes investor pitches, board reviews, and executive workshops. Features intelligent acoustic dampening, 4K camera system with auto-speaker tracking, and private catering staging.',
    category: 'meeting',
    city: 'Lagos',
    neighborhood: 'Ikoyi',
    address: '7 Kingsway Road, Ikoyi, Lagos',
    coordinates: { lat: 6.4531, lng: 3.4359 },
    pricePerHour: 18000,
    pricePerDay: 120000,
    currency: 'NGN',
    rating: 4.98,
    reviewsCount: 42,
    capacity: 14,
    images: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505409859467-3a796fd5798e?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '85-inch 4K Smart Display',
      'Logitech Rally Plus 4K Video Bar',
      'Redundant Generator + Solar',
      'High-Speed Wi-Fi 6',
      'Whiteboard Walls & Markers',
      'Private Nespresso & Refreshments Bar',
      'Executive Leather Seating',
      'Dedicated Hospitality Attendant'
    ],
    hostId: 'user_babajide',
    hostName: 'Babajide Adeleke',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Silent Generators',
    internetSpeedMbps: 500,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 9:00 PM',
      saturday: '9:00 AM - 6:00 PM',
      sunday: 'Closed',
    },
    rules: [
      'Please leave the digital whiteboard wiped after meetings',
      'Outside catering allowed with prior notice'
    ],
    tags: ['Boardroom', 'Ikoyi', 'Zoom Rooms', 'High Tech'],
    isVerified: true,
  },
  {
    id: 'space_3',
    title: 'SoundStage Studio 4: Pro Podcast & Video Suite',
    tagline: 'Sound-isolated creator studio with 4x Shure SM7B mics, Blackmagic 4K cams, and lighting rig.',
    description: 'Turnkey audio and visual studio built for podcasters, YouTube creators, voiceover artists, and interviews. Includes calibrated acoustic treatment, multi-color Aputure lighting, and live stream-ready switching.',
    category: 'podcast',
    city: 'Lagos',
    neighborhood: 'Lekki Phase 1',
    address: 'Admiralty Way, Lekki Phase 1, Lagos',
    coordinates: { lat: 6.4474, lng: 3.4731 },
    pricePerHour: 15000,
    pricePerDay: 95000,
    currency: 'NGN',
    rating: 4.92,
    reviewsCount: 54,
    capacity: 6,
    images: [
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '4x Shure SM7B Dynamic Mics',
      'Rodecaster Pro II Integrated Mixer',
      '3x Sony FX30 4K Cameras',
      'Aputure Amaran LED Softboxes & RGB Backlights',
      'Heavy Acoustic Diffusion Panels (STC 55)',
      'Sound Engineer Assistance Available',
      'High-Speed Cloud Asset Upload (1Gbps)',
      'Green Room & Dressing Area'
    ],
    hostId: 'user_amina',
    hostName: 'Amina Bello',
    hostAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '98% • Under 10 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Triple Grid+Gen+Solar',
    internetSpeedMbps: 1000,
    noiseLevel: 'Soundproofed Studio',
    openingHours: {
      weekdays: '8:00 AM - 11:00 PM',
      saturday: '8:00 AM - 11:00 PM',
      sunday: '12:00 PM - 8:00 PM',
    },
    rules: [
      'No footwear inside the studio floor (slippers provided)',
      'Memory cards (SD/CFExpress) not provided; bring your own storage'
    ],
    tags: ['Podcast', 'Lekki Phase 1', '4K Video', 'Pro Audio'],
    isVerified: true,
  },
  {
    id: 'space_4',
    title: 'Aethel Cyclorama & Daylight Photo Loft',
    tagline: 'Expansive 1,800 sq ft photo & commercial film studio with 18ft ceilings and north-facing light.',
    description: 'A blank canvas for fashion lookbooks, commercial product shoots, music videos, and editorial photography. Includes a 24ft seamless white infinity curve, hair & makeup vanities, and motorized overhead rigging.',
    category: 'photography',
    city: 'Lagos',
    neighborhood: 'Yaba',
    address: 'Commercial Avenue, Yaba, Lagos',
    coordinates: { lat: 6.5095, lng: 3.3711 },
    pricePerHour: 20000,
    pricePerDay: 140000,
    currency: 'NGN',
    rating: 4.88,
    reviewsCount: 31,
    capacity: 25,
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '24ft Curved White Infinity Cove',
      'Natural Floor-to-Ceiling North Daylight',
      'Profoto D2 1000W AirTTL Strobes (x4)',
      'C-Stands, Boom Arms & Sandbags',
      'Professional Steamer & Wardrobe Racks',
      'Dual Hollywood Makeup Mirror Vanities',
      'Roll-up Ground Floor Equipment Loading Bay',
      'Generator Power Backed 24/7'
    ],
    hostId: 'user_chioma',
    hostName: 'Chioma Okonkwo',
    hostAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '95% • Under 30 mins',
    isSuperhost: false,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Silent Generators',
    internetSpeedMbps: 250,
    noiseLevel: 'Collaborative / Vibrant',
    openingHours: {
      weekdays: '7:00 AM - 9:00 PM',
      saturday: '7:00 AM - 9:00 PM',
      sunday: '9:00 AM - 6:00 PM',
    },
    rules: [
      'Cyc wall repainting fee applies if heavy scuffs occur',
      'Smoke/fog machines require prior clearance'
    ],
    tags: ['Photo Studio', 'Cyc Wall', 'Yaba Tech Hub', 'Daylight'],
    isVerified: true,
  },
  {
    id: 'space_5',
    title: 'The Capital Hub Private Team Suite',
    tagline: 'Furnished 8-person private office with dedicated server rack, glass walls, and terrace.',
    description: 'Tailored for expanding tech startups, consulting firms, or remote multinational teams needing a secure, fully-managed workspace in Abuja’s prime diplomatic and commercial district.',
    category: 'private_office',
    city: 'Abuja',
    neighborhood: 'Maitama',
    address: 'Gana Street, Maitama, Abuja',
    coordinates: { lat: 9.0882, lng: 7.4983 },
    pricePerHour: 12000,
    pricePerDay: 75000,
    currency: 'NGN',
    rating: 4.96,
    reviewsCount: 39,
    capacity: 8,
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Dedicated Biometric Door Lock',
      'Sound-Dampened Acoustic Glass',
      'Executive Sit-Stand Desks',
      'Private Server / LAN Switch Access',
      'Access to Central Cafeteria & Courtyard',
      '24/7 Security & Diplomatic Zone Patrol',
      'Continuous 100% Redundant Power'
    ],
    hostId: 'user_tunde',
    hostName: 'Tunde Adebayo',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Under 5 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: '24/7 Solar & Inverter',
    internetSpeedMbps: 400,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '24 Hours',
      saturday: '24 Hours',
      sunday: '24 Hours',
    },
    rules: [
      'Keycard & biometric registration required on first arrival',
      'Guest sign-in at building reception'
    ],
    tags: ['Private Suite', 'Maitama Abuja', '24/7 Access', 'Diplomatic'],
    isVerified: true,
  },
  {
    id: 'space_6',
    title: 'The Atrium Innovation Amphitheatre & Event Hall',
    tagline: 'Modern 120-seat tech demo hall with tier seating, dual LED walls, and acoustic canopy.',
    description: 'The premier venue for product launches, hackathons, investor demo days, tech conferences, and workshops in Port Harcourt. Equipped with full production sound and streaming control booth.',
    category: 'event',
    city: 'Port Harcourt',
    neighborhood: 'GRA Phase 2',
    address: 'Tombia Street, GRA Phase 2, Port Harcourt',
    coordinates: { lat: 4.8156, lng: 7.0498 },
    pricePerHour: 45000,
    pricePerDay: 320000,
    currency: 'NGN',
    rating: 4.91,
    reviewsCount: 22,
    capacity: 120,
    images: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '120 Ergonomic Stadium Seats',
      'Dual P2.5 High-Res LED Walls (16x9ft)',
      'Line-Array Sound System + 4 Wireless Lapels/Handhelds',
      'Live Streaming Broadcast Control Room',
      'Dedicated High-Capacity Generator Array',
      'Catering Prep Kitchen & Outdoor Networking Terrace',
      'Valet & Secure 60-Car Parking Lot'
    ],
    hostId: 'user_babajide',
    hostName: 'Babajide Adeleke',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '96% • Under 1 hour',
    isSuperhost: true,
    instantBooking: false,
    hasBackupPower: true,
    backupPowerType: 'Dual Silent Generators',
    internetSpeedMbps: 600,
    noiseLevel: 'Collaborative / Vibrant',
    openingHours: {
      weekdays: '8:00 AM - 10:00 PM',
      saturday: '8:00 AM - 11:00 PM',
      sunday: '10:00 AM - 10:00 PM',
    },
    rules: [
      'Event setup and breakdown must fit within the booked time window',
      'Security marshals required for events exceeding 80 attendees'
    ],
    tags: ['Event Space', 'Port Harcourt', 'LED Wall', 'Demo Day'],
    isVerified: true,
  },
  {
    id: 'space_regus_africare',
    title: 'Regus Africa Re Centre (Victoria Island)',
    tagline: 'Global enterprise workspace with redundant high-speed fiber and executive suites.',
    description: 'Position your business in one of Lagos’ most prestigious corporate addresses. Located in the landmark Africa Re building on Karimu Kotun in Victoria Island, this Regus centre provides international-standard ergonomic seating, enterprise-grade fiber internet, 24/7 dedicated dual generator power, and executive boardroom facilities.',
    category: 'coworking',
    city: 'Lagos',
    neighborhood: 'Victoria Island',
    address: 'Plot 1679 Karimu Kotun St, Victoria Island, Lagos',
    coordinates: { lat: 6.4278, lng: 3.4225 },
    pricePerHour: 4500,
    pricePerDay: 28000,
    currency: 'NGN',
    rating: 4.97,
    reviewsCount: 94,
    capacity: 40,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Regus Global Network Standards',
      '24/7 Dual Redundant Gen Power',
      'High-Speed Enterprise Fiber',
      'Executive Meeting Rooms',
      'Business Lounge Access',
      'Multilingual Concierge Support',
      'Secure Underground Parking',
      'Artisanal Coffee & Tea Bar'
    ],
    hostId: 'user_tunde',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Silent Generators + Online UPS',
    internetSpeedMbps: 600,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:00 AM - 10:00 PM',
      saturday: '8:00 AM - 8:00 PM',
      sunday: '9:00 AM - 6:00 PM',
    },
    rules: [
      'Business casual dress code in executive lounges',
      'Digital OFIS pass scan at lobby turnstiles'
    ],
    tags: ['Regus Center', 'Victoria Island', 'Global Partner', 'Executive Suite', 'Instant Book'],
    isVerified: true,
    floorPlanSeats: [
      { id: 'regus-vi-01', label: 'Dedicated Desk A1', type: 'dedicated_desk', status: 'available', pricePerHour: 4500, x: 20, y: 25 },
      { id: 'regus-vi-02', label: 'Dedicated Desk A2', type: 'dedicated_desk', status: 'available', pricePerHour: 4500, x: 35, y: 25 },
      { id: 'regus-vi-03', label: 'Hot Desk B1', type: 'hot_desk', status: 'available', pricePerHour: 4500, x: 55, y: 25 },
      { id: 'regus-vi-04', label: 'Hot Desk B2', type: 'hot_desk', status: 'occupied', pricePerHour: 4500, x: 70, y: 25 },
      { id: 'regus-vi-booth', label: 'Executive Booth', type: 'booth', status: 'available', pricePerHour: 6000, x: 80, y: 70 },
    ]
  },
  {
    id: 'space_regus_mulliner',
    title: 'Regus Mulliner Towers (Ikoyi)',
    tagline: 'Prestigious corporate business center on Alfred Rewane Road with skyline views.',
    description: 'Regus Mulliner Towers offers world-class workspace in the prestigious commercial artery of Ikoyi. Complete with modern meeting rooms, business lounges, sound-treated phone booths, dedicated fiber connectivity, and multi-tier security.',
    category: 'private_office',
    city: 'Lagos',
    neighborhood: 'Ikoyi',
    address: '39 Alfred Rewane (Kingsway) Rd, Ikoyi, Lagos',
    coordinates: { lat: 6.4520, lng: 3.4385 },
    pricePerHour: 5000,
    pricePerDay: 32000,
    currency: 'NGN',
    rating: 4.96,
    reviewsCount: 86,
    capacity: 35,
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Regus Global Network Standards',
      '24/7 Redundant Power',
      'Dual 500Mbps High-Speed Fiber',
      'Executive Boardrooms',
      'Concierge & Mail Handling',
      'Dedicated Secure Parking',
      'Private Kitchenette & Barista'
    ],
    hostId: 'user_tunde',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '99% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Inverter Grid',
    internetSpeedMbps: 500,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 9:00 PM',
      saturday: '9:00 AM - 6:00 PM',
      sunday: 'Closed',
    },
    rules: [
      'Access card or digital QR code required at main elevator lobby'
    ],
    tags: ['Regus Center', 'Ikoyi', 'Global Partner', 'Corporate Hub'],
    isVerified: true,
  },
  {
    id: 'space_regus_landmark',
    title: 'Regus Landmark Towers (Victoria Island)',
    tagline: 'Oceanview corporate workspace and tech suites in the Landmark commercial district.',
    description: 'Situated in the vibrant Landmark ecosystem overlooking the Atlantic coastline in Victoria Island, this Regus centre provides founders, executives, and visiting delegations beachside prestige combined with enterprise infrastructure.',
    category: 'coworking',
    city: 'Lagos',
    neighborhood: 'Victoria Island',
    address: '5b Water Corporation Drive, Victoria Island, Lagos',
    coordinates: { lat: 6.4230, lng: 3.4470 },
    pricePerHour: 5500,
    pricePerDay: 35000,
    currency: 'NGN',
    rating: 4.98,
    reviewsCount: 112,
    capacity: 50,
    images: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Oceanfront Coastline Views',
      'Regus Global Standards',
      '24/7 Continuous Power Grid',
      'Enterprise Wi-Fi 6 (800Mbps)',
      'Event & Strategy Suites',
      'Access to Landmark Dining & Retail',
      'Secure Multi-Story Valet Parking'
    ],
    hostId: 'user_babajide',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Solar Array',
    internetSpeedMbps: 800,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:30 AM - 10:00 PM',
      saturday: '8:30 AM - 8:00 PM',
      sunday: '10:00 AM - 6:00 PM',
    },
    rules: [
      'No loud calls in the quiet work commons'
    ],
    tags: ['Regus Center', 'Landmark VI', 'Oceanview', 'Global Partner', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_wings',
    title: 'Regus The Wings Office Complex (Victoria Island)',
    tagline: 'LEED-certified waterfront towers on Ozumba Mbadiwe with private jetty access.',
    description: 'The Wings is an iconic architectural landmark on Five Cowries Creek. Regus suites within The Wings offer LEED-certified luxury, high-speed fiber ring network, executive boardrooms, and waterfront dining.',
    category: 'meeting',
    city: 'Lagos',
    neighborhood: 'Victoria Island',
    address: '17A Ozumba Mbadiwe Ave, Victoria Island, Lagos',
    coordinates: { lat: 6.4382, lng: 3.4140 },
    pricePerHour: 6000,
    pricePerDay: 38000,
    currency: 'NGN',
    rating: 4.99,
    reviewsCount: 78,
    capacity: 30,
    images: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Five Cowries Waterfront View & Jetty',
      'Regus Global Standards',
      'LEED Certified Complex',
      '100% Uninterrupted Power',
      '1Gbps Dedicated Fiber Ring',
      'Private Valet Parking',
      '4K Smart Boardrooms'
    ],
    hostId: 'user_babajide',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '98% • Under 10 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Triple Grid + Gen + UPS',
    internetSpeedMbps: 1000,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 9:00 PM',
      saturday: '9:00 AM - 6:00 PM',
      sunday: 'Closed',
    },
    rules: [
      'Prior booking required for waterfront boardroom terrace'
    ],
    tags: ['Regus Center', 'The Wings VI', 'Grade A', 'Waterfront', 'Executive'],
    isVerified: true,
  },
  {
    id: 'space_regus_churchgate',
    title: 'Regus Churchgate Tower 2 (Victoria Island)',
    tagline: 'Financial district suites with full business concierge on Churchgate Street.',
    description: 'Located in Churchgate Tower 2 at the epicenter of the Lagos commercial banking corridor. Fully equipped flexible hot desks, private offices, and conferencing facilities with on-demand catering.',
    category: 'coworking',
    city: 'Lagos',
    neighborhood: 'Victoria Island',
    address: 'Plot PC 30, Churchgate St, Victoria Island, Lagos',
    coordinates: { lat: 6.4310, lng: 3.4190 },
    pricePerHour: 4200,
    pricePerDay: 26000,
    currency: 'NGN',
    rating: 4.93,
    reviewsCount: 51,
    capacity: 28,
    images: [
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Regus Global Standards',
      '24/7 Power Assurance',
      'Fast Fiber Internet',
      'Espresso & Tea Bar',
      'Acoustic Phone Booths',
      'Multilingual Reception'
    ],
    hostId: 'user_tunde',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '99% • Under 5 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: '24/7 Dual Generators',
    internetSpeedMbps: 450,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 8:00 PM',
      saturday: '9:00 AM - 5:00 PM',
      sunday: 'Closed',
    },
    rules: [
      'Digital pass scan required at turnstiles'
    ],
    tags: ['Regus Center', 'Churchgate VI', 'Financial District', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_abuja',
    title: 'Regus Grand Square (CBD Abuja)',
    tagline: 'Diplomatic & executive office suites in Abuja’s Central Business District.',
    description: 'Located along Muhammadu Buhari Way in the core Central Business District of Abuja, Regus Grand Square offers proximity to ministries, embassies, and corporate headquarters with top-tier security and high-speed fiber.',
    category: 'private_office',
    city: 'Abuja',
    neighborhood: 'Central Business District',
    address: 'Plot 270 Muhammadu Buhari Way, Central Business District, Abuja',
    coordinates: { lat: 9.0579, lng: 7.4951 },
    pricePerHour: 4000,
    pricePerDay: 25000,
    currency: 'NGN',
    rating: 4.95,
    reviewsCount: 63,
    capacity: 30,
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Regus Global Standards',
      'Diplomatic Zone Security',
      '24/7 Solar & Gen Redundancy',
      '400Mbps Fiber',
      'Boardrooms & Training Rooms',
      'Secure Basement Parking'
    ],
    hostId: 'user_tunde',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Under 5 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: '24/7 Solar & Inverter + Generator',
    internetSpeedMbps: 400,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:30 AM - 9:00 PM',
      saturday: '8:00 AM - 6:00 PM',
      sunday: '10:00 AM - 4:00 PM',
    },
    rules: [
      'Visitor check-in at security desk'
    ],
    tags: ['Regus Center', 'Abuja CBD', 'Diplomatic Hub', 'Global Standards'],
    isVerified: true,
  },
  {
    id: 'space_regus_ph',
    title: 'Regus Trans Amadi Centre (Port Harcourt)',
    tagline: 'Industrial & energy sector workspace in the commercial hub of Port Harcourt.',
    description: 'Regus Trans Amadi Centre serves energy multinationals, engineering consultancies, and remote teams in Port Harcourt with heavy industrial power backups, corporate meeting spaces, and verified security.',
    category: 'coworking',
    city: 'Port Harcourt',
    neighborhood: 'Trans Amadi',
    address: 'Plot 128, Trans Amadi Industrial Layout, Port Harcourt, Rivers State',
    coordinates: { lat: 4.8210, lng: 7.0250 },
    pricePerHour: 3800,
    pricePerDay: 24000,
    currency: 'NGN',
    rating: 4.92,
    reviewsCount: 47,
    capacity: 25,
    images: [
      'https://images.unsplash.com/photo-1505409859467-3a796fd5798e?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1505409859467-3a796fd5798e?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Regus Global Standards',
      'Heavy Industrial 24/7 Power',
      'High-Speed Enterprise Fiber',
      'Video Conferencing Suite',
      'On-Site Security Staff',
      'Ample Gated Parking'
    ],
    hostId: 'user_babajide',
    hostName: 'Regus Nigeria Network',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '96% • Under 1 hour',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Silent Industrial Generators',
    internetSpeedMbps: 350,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 8:00 PM',
      saturday: '9:00 AM - 5:00 PM',
      sunday: 'Closed',
    },
    rules: [
      'Security registration on arrival'
    ],
    tags: ['Regus Center', 'Port Harcourt', 'Energy Hub', 'Global Partner'],
    isVerified: true,
  },
  {
    id: 'space_regus_nairobi_vienna',
    title: 'Regus Vienna Court (Nairobi, Kenya)',
    tagline: 'Eco-certified platinum enterprise workspace in Nairobi’s diplomatic & tech corridor.',
    description: 'Vienna Court is East Africa’s premier Gold LEED certified commercial building located along State House Crescent in Nairobi. This Regus centre offers dual redundant fiber rings, solar backup power, landscaped waterfall courtyards, video conferencing boardrooms, and executive private offices.',
    category: 'coworking',
    city: 'Nairobi',
    country: 'Kenya',
    region: 'East Africa',
    neighborhood: 'State House Crescent / Kilimani',
    address: 'Vienna Court, State House Crescent, Nairobi, Kenya',
    coordinates: { lat: -1.2864, lng: 36.8065 },
    pricePerHour: 4800,
    pricePerDay: 29000,
    currency: 'NGN',
    rating: 4.98,
    reviewsCount: 104,
    capacity: 45,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Gold LEED Eco Certified',
      '100% Dual Power Redundancy',
      '1Gbps Enterprise Fiber',
      'Lush Courtyard & Waterfall Cafe',
      'High-Tech Video Suites',
      'Secure Underground Parking',
      'Concierge & Multilingual Support'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus East Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Solar Microgrid',
    internetSpeedMbps: 650,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:30 AM - 9:00 PM',
      saturday: '8:30 AM - 6:00 PM',
      sunday: 'Closed',
    },
    rules: ['Digital visitor check-in at reception', 'Business casual dress in shared lounge'],
    tags: ['Regus Center', 'Nairobi', 'Kenya', 'East Africa', 'Global Partner', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_nairobi_delta',
    title: 'Regus Delta Corner (Westlands, Nairobi)',
    tagline: 'Tech epicenter workspace in the heart of Westlands commercial hub.',
    description: 'Located in the prominent Delta Corner Towers at the junction of Chiromo Road and Ring Road Westlands, this centre puts your business in the silicon savannah corridor surrounded by multinationals, venture funds, and vibrant dining.',
    category: 'private_office',
    city: 'Nairobi',
    country: 'Kenya',
    region: 'East Africa',
    neighborhood: 'Westlands',
    address: 'Delta Corner Tower A, Chiromo Rd, Westlands, Nairobi, Kenya',
    coordinates: { lat: -1.2680, lng: 36.8040 },
    pricePerHour: 4600,
    pricePerDay: 28000,
    currency: 'NGN',
    rating: 4.95,
    reviewsCount: 88,
    capacity: 35,
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Regus Global Network Standards',
      '24/7 Redundant Power Plant',
      'Dual High-Speed Fiber Lines',
      'Executive Boardrooms',
      'Skyline View Lounges',
      'On-Site Coffee Barista'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus East Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '99% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + UPS',
    internetSpeedMbps: 500,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 8:30 PM',
      saturday: '9:00 AM - 5:00 PM',
      sunday: 'Closed',
    },
    rules: ['Scan Regus QR Pass at security turnstiles'],
    tags: ['Regus Center', 'Westlands', 'Nairobi', 'Kenya', 'Global Partner'],
    isVerified: true,
  },
  {
    id: 'space_regus_sandton',
    title: 'Regus Sandton City (Johannesburg, South Africa)',
    tagline: 'Africa’s richest square mile: prestigious business suites connected to Sandton City.',
    description: 'Located in the iconic Atrium on 5th directly connected to Sandton City and the Gautrain Station. This premier South African Regus location provides direct access to financial exchanges, corporate headquarters, and high-speed infrastructure.',
    category: 'coworking',
    city: 'Johannesburg',
    country: 'South Africa',
    region: 'Southern Africa',
    neighborhood: 'Sandton CBD',
    address: 'Atrium on 5th, Sandton City, 5th St, Sandton, Johannesburg, South Africa',
    coordinates: { lat: -26.1076, lng: 28.0567 },
    pricePerHour: 5200,
    pricePerDay: 32000,
    currency: 'NGN',
    rating: 4.99,
    reviewsCount: 142,
    capacity: 50,
    images: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Direct Gautrain & Sandton Mall Walkway',
      '100% Uninterrupted Power (Zero Load-Shedding)',
      '1Gbps Dedicated Tier 1 Fiber',
      'Executive Strategy Suites',
      'Dedicated Phone Booths',
      'Secure Multi-Level Parking'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus South Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Solar UPS (Load-Shedding Proof)',
    internetSpeedMbps: 800,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:00 AM - 9:00 PM',
      saturday: '8:00 AM - 6:00 PM',
      sunday: '10:00 AM - 4:00 PM',
    },
    rules: ['Digital check-in at Level 9 reception'],
    tags: ['Regus Center', 'Sandton', 'Johannesburg', 'South Africa', 'Southern Africa', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_capetown_convention',
    title: 'Regus Convention Tower (Cape Town, South Africa)',
    tagline: 'Waterfront & Table Mountain views beside Cape Town International Convention Centre.',
    description: 'Perched in the prestigious Convention Tower on the Cape Town Foreshore, adjacent to the CTICC and minutes from the V&A Waterfront. Enjoy floor-to-ceiling vistas of Table Mountain while working in top-tier executive suites.',
    category: 'meeting',
    city: 'Cape Town',
    country: 'South Africa',
    region: 'Southern Africa',
    neighborhood: 'Foreshore / Waterfront Corridor',
    address: '1st Floor, Convention Tower, Cnr Heerengracht & Walter Sisulu Ave, Foreshore, Cape Town',
    coordinates: { lat: -33.9160, lng: 18.4280 },
    pricePerHour: 5500,
    pricePerDay: 34000,
    currency: 'NGN',
    rating: 4.98,
    reviewsCount: 118,
    capacity: 40,
    images: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Table Mountain Panoramic Views',
      'Adjacent to CTICC Conference Centre',
      'Load-Shedding Free Continuous Power',
      'High-Speed Symmetrical Fiber (750Mbps)',
      'Acoustic Boardrooms',
      'Barista Coffee & Rooftop Terrace'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus South Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '99% • Under 5 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Grid Redundancy',
    internetSpeedMbps: 750,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 8:00 PM',
      saturday: '9:00 AM - 5:00 PM',
      sunday: 'Closed',
    },
    rules: ['OFIS digital pass required for CTICC complex access'],
    tags: ['Regus Center', 'Cape Town', 'Table Mountain', 'South Africa', 'Global Partner'],
    isVerified: true,
  },
  {
    id: 'space_regus_accra_roman',
    title: 'Regus Roman Ridge (Accra, Ghana)',
    tagline: 'Prime diplomatic district workspace 10 minutes from Kotoka International Airport.',
    description: 'Set in Accra’s tranquil and upscale Roman Ridge neighborhood, this Regus centre offers swift access to both Kotoka Airport and the Central Business District. Featuring full power backup, high-speed fiber, lush garden lounges, and boardrooms.',
    category: 'coworking',
    city: 'Accra',
    country: 'Ghana',
    region: 'West Africa',
    neighborhood: 'Roman Ridge / Airport Residential',
    address: 'Roman Ridge Shopping Arcade, 8 Sir Arku Korsah Rd, Roman Ridge, Accra, Ghana',
    coordinates: { lat: 5.6020, lng: -0.1920 },
    pricePerHour: 4300,
    pricePerDay: 27000,
    currency: 'NGN',
    rating: 4.96,
    reviewsCount: 76,
    capacity: 35,
    images: [
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '10 Mins to Kotoka International Airport',
      '24/7 Redundant Gen + Solar Inverter',
      'High-Speed Enterprise Fiber (500Mbps)',
      'Garden Patio & Breakout Lounges',
      'Video Boardrooms & Printing Pods',
      'Secure Gated Compound Parking'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus West Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '98% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Solar Array',
    internetSpeedMbps: 500,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:30 AM - 8:30 PM',
      saturday: '8:30 AM - 5:00 PM',
      sunday: 'Closed',
    },
    rules: ['Security check-in at main entrance gate'],
    tags: ['Regus Center', 'Accra', 'Ghana', 'West Africa', 'Airport Corridor', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_kigali_heights',
    title: 'Regus Kigali Heights (Kigali, Rwanda)',
    tagline: 'Flagship landmark workspace opposite Kigali Convention Centre in Kimihurura.',
    description: 'Located in the award-winning Kigali Heights complex right across from the iconic Kigali Convention Centre dome. This modern facility serves East Africa’s fastest growing tech and diplomatic hub with premier office facilities and uninterrupted high-speed internet.',
    category: 'coworking',
    city: 'Kigali',
    country: 'Rwanda',
    region: 'East Africa',
    neighborhood: 'Kimihurura / Convention District',
    address: '5th Floor, Kigali Heights West Wing, KG 7 Ave, Kimihurura, Kigali, Rwanda',
    coordinates: { lat: -1.9536, lng: 30.0934 },
    pricePerHour: 4200,
    pricePerDay: 26000,
    currency: 'NGN',
    rating: 4.97,
    reviewsCount: 68,
    capacity: 32,
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Opposite Kigali Convention Centre',
      '24/7 Continuous Power Grid + Gen',
      'High-Speed 400Mbps Fiber',
      'Rooftop Terrace & Banking Amenities',
      'Smart Presentation Boardrooms',
      'Ample Underground Parking'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus East Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '100% • Under 5 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Industrial Generators + UPS',
    internetSpeedMbps: 400,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 8:00 PM',
      saturday: '8:30 AM - 4:30 PM',
      sunday: 'Closed',
    },
    rules: ['Digital badge check-in at West Wing reception'],
    tags: ['Regus Center', 'Kigali', 'Rwanda', 'East Africa', 'Kigali Heights', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_cairo_nile',
    title: 'Regus Nile City Towers (Cairo, Egypt)',
    tagline: 'Prestigious waterfront skyscraper on the Nile Corniche in downtown Cairo.',
    description: 'Located in the prestigious Nile City South Tower along the Nile River in Cairo. This Regus centre offers panoramic river views, high-end shopping and hotel facilities within the complex, 24/7 security, and modern conferencing spaces.',
    category: 'private_office',
    city: 'Cairo',
    country: 'Egypt',
    region: 'North Africa',
    neighborhood: 'Corniche El Nil / Ramlet Boulaq',
    address: '22nd Floor, Nile City South Tower, 2005C Corniche El Nil, Ramlet Boulaq, Cairo, Egypt',
    coordinates: { lat: 30.0715, lng: 31.2285 },
    pricePerHour: 4900,
    pricePerDay: 30000,
    currency: 'NGN',
    rating: 4.96,
    reviewsCount: 92,
    capacity: 40,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Nile River Panoramic Views',
      'Nile City Mall & Fairmont Hotel Access',
      'Continuous 24/7 Redundant Power',
      '600Mbps High-Speed Enterprise Fiber',
      'Executive Video Boardrooms',
      'Concierge & Mail Services'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus North Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '99% • Instant',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Skyscraper Microgrid',
    internetSpeedMbps: 600,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 9:00 PM',
      saturday: '9:00 AM - 6:00 PM',
      sunday: '8:00 AM - 8:00 PM',
    },
    rules: ['Security check-in at South Tower ground lobby'],
    tags: ['Regus Center', 'Cairo', 'Egypt', 'North Africa', 'Nile City', 'Instant Book'],
    isVerified: true,
  },
  {
    id: 'space_regus_casablanca_twin',
    title: 'Regus Twin Center (Casablanca, Morocco)',
    tagline: 'Iconic commercial twin towers in Maarif financial district of Casablanca.',
    description: 'Set inside Casablanca’s most recognizable commercial landmark—the Twin Center in Maarif. This Regus centre delivers prime business prestige in Morocco’s financial capital with multilingual staff, executive lounges, and fiber connectivity.',
    category: 'coworking',
    city: 'Casablanca',
    country: 'Morocco',
    region: 'North Africa',
    neighborhood: 'Maarif / Boulevard Zerktouni',
    address: 'Tour Ouest, 16th Floor, Twin Center, Angle Bd Zerktouni & Bd Al Massira, Casablanca, Morocco',
    coordinates: { lat: 33.5868, lng: -7.6324 },
    pricePerHour: 4700,
    pricePerDay: 29000,
    currency: 'NGN',
    rating: 4.94,
    reviewsCount: 81,
    capacity: 36,
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Landmark Twin Towers Address',
      '24/7 Redundant Power Grid',
      'High-Speed 500Mbps Fiber',
      'Multilingual Support (French, Arabic, English)',
      'Executive Strategy Suites',
      'Direct Access to Shopping & Cafes'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus North Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '98% • Under 10 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + UPS Inverter',
    internetSpeedMbps: 500,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 8:00 PM',
      saturday: '8:30 AM - 5:00 PM',
      sunday: 'Closed',
    },
    rules: ['Digital pass scan at West Tower turnstiles'],
    tags: ['Regus Center', 'Casablanca', 'Morocco', 'North Africa', 'Twin Center', 'Global Partner'],
    isVerified: true,
  },
  {
    id: 'space_regus_abidjan_ccia',
    title: 'Regus CCIA Tower (Abidjan, Ivory Coast)',
    tagline: 'Heart of Plateau business district overlooking the Ébrié Lagoon in Abidjan.',
    description: 'Located in the historic CCIA Tower in Le Plateau, Abidjan’s central business and government quarter. Offers seamless connection to major banks, diplomatic embassies, and corporate headquarters with top-tier power backup and fiber optics.',
    category: 'coworking',
    city: 'Abidjan',
    country: 'Ivory Coast',
    region: 'West Africa',
    neighborhood: 'Le Plateau',
    address: 'Immeuble CCIA, Avenue Jean-Paul II, Le Plateau, Abidjan, Côte d’Ivoire',
    coordinates: { lat: 5.3255, lng: -4.0205 },
    pricePerHour: 4400,
    pricePerDay: 27500,
    currency: 'NGN',
    rating: 4.93,
    reviewsCount: 59,
    capacity: 30,
    images: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Prime Plateau Business District',
      '24/7 Redundant Generators',
      '450Mbps High-Speed Fiber',
      'French & English Concierge',
      'Video Conference Boardrooms',
      'Guarded Secure Parking'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus West Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '97% • Under 15 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Silent Generators + UPS',
    internetSpeedMbps: 450,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '7:30 AM - 8:00 PM',
      saturday: '8:30 AM - 4:00 PM',
      sunday: 'Closed',
    },
    rules: ['Identification check at building reception'],
    tags: ['Regus Center', 'Abidjan', 'Ivory Coast', 'West Africa', 'Le Plateau', 'Global Partner'],
    isVerified: true,
  },
  {
    id: 'space_regus_dakar_atryum',
    title: 'Regus Atryum Center (Dakar, Senegal)',
    tagline: 'Coastal capital workspace along Route de Ouakam in Dakar.',
    description: 'Located in the Atryum Center along the busy Route de Ouakam corridor in Dakar, minutes from Fann Résidence and the Atlantic coast. Provides flexible shared desks, private executive suites, and corporate conferencing.',
    category: 'coworking',
    city: 'Dakar',
    country: 'Senegal',
    region: 'West Africa',
    neighborhood: 'Fann Résidence / Route de Ouakam',
    address: 'Atryum Center, Km 8 Route de Ouakam, Dakar, Senegal',
    coordinates: { lat: 14.7167, lng: -17.4677 },
    pricePerHour: 4300,
    pricePerDay: 26500,
    currency: 'NGN',
    rating: 4.92,
    reviewsCount: 54,
    capacity: 28,
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505409859467-3a796fd5798e?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '24/7 Redundant Power',
      'High-Speed 400Mbps Fiber',
      'Bilingual Support (French & English)',
      'Modern Boardrooms',
      'Espresso & Refreshment Bar',
      'Gated Parking Area'
    ],
    hostId: 'user_regus_africa',
    hostName: 'Regus West Africa Network',
    hostAvatar: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=300&auto=format&fit=crop&q=80',
    hostResponseRate: '96% • Under 30 mins',
    isSuperhost: true,
    instantBooking: true,
    hasBackupPower: true,
    backupPowerType: 'Dual Generators + Solar Backup',
    internetSpeedMbps: 400,
    noiseLevel: 'Silent / Library',
    openingHours: {
      weekdays: '8:00 AM - 7:30 PM',
      saturday: '9:00 AM - 4:00 PM',
      sunday: 'Closed',
    },
    rules: ['Registration at ground floor security'],
    tags: ['Regus Center', 'Dakar', 'Senegal', 'West Africa', 'Global Partner'],
    isVerified: true,
  }
];

export const POPULAR_CITIES = [
  'Lagos', 
  'Abuja', 
  'Port Harcourt', 
  'Nairobi', 
  'Johannesburg', 
  'Cape Town', 
  'Accra', 
  'Kigali', 
  'Cairo', 
  'Casablanca'
] as const;

export const CATEGORY_METADATA = [
  { id: 'all', label: 'All Spaces', icon: 'LayoutGrid', description: 'Explore all verified workspaces and studios across Nigeria' },
  { id: 'coworking', label: 'Work (Desks)', icon: 'Laptop', description: 'Hot desks, dedicated desks & quiet lounges' },
  { id: 'meeting', label: 'Meet (Boardrooms)', icon: 'Users', description: 'Executive boardrooms & strategy suites' },
  { id: 'podcast', label: 'Record (Podcasts)', icon: 'Mic', description: 'Acoustically isolated audio & video suites' },
  { id: 'photography', label: 'Create (Studios)', icon: 'Camera', description: 'Cyclorama infinity coves & daylight photo lofts' },
  { id: 'private_office', label: 'Private Offices', icon: 'Briefcase', description: 'Dedicated lockable suites for growing teams' },
  { id: 'event', label: 'Event Venues', icon: 'Sparkles', description: 'Tech demo halls, workshops & pitch spaces' },
];
