import { Space, UserProfile, SearchFilters, Review } from './types';

export const INITIAL_USER: UserProfile = {
  id: 'user-001',
  name: 'Babatunde Adeyemi',
  email: 'tunde.adeyemi@paystack.com',
  phone: '+234 802 345 6789',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  role: 'user',
  company: 'Fintech Systems Ltd',
  bio: 'Software engineer and tech founder based in Lagos. Frequently booking focus desks and meeting pods.',
  walletBalanceNgn: 85000,
  savedSpaceIds: ['space-vi-hive', 'space-ikoyi-glass'],
  createdAt: '2024-01-15T10:30:00Z',
};

export const INITIAL_HOST: UserProfile = {
  id: 'host-001',
  name: 'Funke Akindele-Cole',
  email: 'funke@creativespace.ng',
  phone: '+234 803 987 6543',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
  role: 'host',
  company: 'OFIS Premier Workspaces',
  bio: 'Hospitality & commercial real estate manager operating 4 serviced hubs across Victoria Island and Ikoyi.',
  walletBalanceNgn: 420000,
  savedSpaceIds: [],
  createdAt: '2023-08-10T12:00:00Z',
};

export const GUEST_USER: UserProfile = {
  id: 'guest-user',
  name: 'Guest Explorer',
  email: 'guest@ofis.ng',
  phone: '+234 800 000 0000',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80',
  role: 'user',
  company: 'Independent Professional',
  bio: 'Exploring workspaces and focus hubs.',
  walletBalanceNgn: 0,
  savedSpaceIds: [],
  createdAt: '2024-01-01T00:00:00Z',
};

export const POPULAR_CITIES = [
  'Lagos',
  'Abuja',
  'Port Harcourt',
  'Ibadan',
  'Enugu',
  'Accra',
  'Nairobi',
  'Kigali',
];

export const CATEGORY_METADATA = [
  {
    id: 'all',
    label: 'All Workspaces',
    description: 'Explore entire curated directory',
    icon: 'Sparkles',
    count: 24,
  },
  {
    id: 'coworking',
    label: 'Coworking & Desks',
    description: 'Hot desks, ergonomic seating & quiet booths',
    icon: 'Laptop',
    count: 8,
  },
  {
    id: 'private_office',
    label: 'Private Offices',
    description: 'Enclosed suites for teams & executive privacy',
    icon: 'Building2',
    count: 4,
  },
  {
    id: 'meeting',
    label: 'Meeting & Boardrooms',
    description: 'AV conferencing, 4K displays & client presentation rooms',
    icon: 'Presentation',
    count: 5,
  },
  {
    id: 'podcast',
    label: 'Podcast Studios',
    description: 'Shure SM7B mics, acoustic dampening & multi-cam rigs',
    icon: 'Mic2',
    count: 3,
  },
  {
    id: 'photography',
    label: 'Photo & Film Sets',
    description: 'Cyclorama infinity walls, continuous lights & prep suites',
    icon: 'Camera',
    count: 2,
  },
  {
    id: 'event',
    label: 'Event Halls & Lounges',
    description: 'Keynotes, tech meetups, demos & corporate mixers',
    icon: 'Users',
    count: 2,
  },
];

export const MOCK_SPACES: Space[] = [
  {
    id: 'space-vi-hive',
    title: 'The Hive Coworking & Tech Hub',
    tagline: 'High-speed internet, dual generator backup & specialty espresso bar',
    description: 'Prime Victoria Island workspace designed for high-growth tech teams, remote engineers, and creative founders. Features Herman Miller ergonomic task chairs, silent call pods, dual redundant diesel generators, high-speed internet, and a rooftop networking lounge.',
    category: 'coworking',
    city: 'Lagos',
    state: 'Lagos State',
    neighborhood: 'Victoria Island',
    address: '14B Karimu Kotun Street, Victoria Island, Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    pricePerHour: 3500,
    pricePerDay: 20000,
    capacity: 45,
    hasBackupPower: true,
    powerType: 'Heavy Duty Gen + Solar Hybrid',
    powerUptimeGuaranteePercent: 99.9,
    internetSpeedMbps: 300,
    internetIsp: 'MainOne Dedicated Fiber',
    noiseLevel: 'Moderate / Focus Buzz',
    images: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '24/7 Solar & Gen Power',
      '300Mbps High-Speed Internet',
      'Ergonomic Herman Miller Chairs',
      'Artisanal Coffee & Tea Bar',
      'Acoustic Phone Booths',
      'Secure Electronic Access Turnstiles',
      'Ethernet / Cat6 LAN Ports',
      'Outdoor Rooftop Garden',
    ],
    rating: 4.9,
    reviewsCount: 128,
    host: {
      id: 'host-001',
      name: 'Funke Akindele-Cole',
      companyName: 'OFIS Premier Workspaces',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 803 987 6543',
      email: 'funke@creativespace.ng',
      responseRatePercent: 99,
      responseTimeMinutes: 5,
      totalSpaces: 4,
      rating: 4.95,
    },
    operatingHours: {
      open: '07:00',
      close: '22:00',
      days: 'Mon - Sat (Sunday: 10:00 - 18:00)',
    },
    rules: [
      'Quiet phone conversations inside acoustic booths only',
      'No hot or pungent food at individual work desks',
      'Digital pass scan required at turnstiles',
    ],
    tags: ['High-Speed Internet', 'Solar Backed', 'Victoria Island', 'Instant Book'],
    isVerified: true,
    isSuperhost: true,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'available_now',
    occupancyLevel: 'low',
    floorPlanSeats: [
      { id: 'desk-01', label: 'Desk 01 (Window View)', type: 'dedicated_desk', status: 'available', pricePerHour: 3500, x: 20, y: 30 },
      { id: 'desk-02', label: 'Desk 02 (Window View)', type: 'dedicated_desk', status: 'available', pricePerHour: 3500, x: 35, y: 30 },
      { id: 'desk-03', label: 'Desk 03 (Standing Desk)', type: 'dedicated_desk', status: 'occupied', pricePerHour: 4000, x: 50, y: 30 },
      { id: 'desk-04', label: 'Desk 04 (Hot Desk Central)', type: 'hot_desk', status: 'available', pricePerHour: 3000, x: 20, y: 60 },
      { id: 'desk-05', label: 'Desk 05 (Hot Desk Central)', type: 'hot_desk', status: 'reserved', pricePerHour: 3000, x: 35, y: 60 },
      { id: 'booth-01', label: 'Acoustic Focus Pod A', type: 'booth', status: 'available', pricePerHour: 4500, x: 75, y: 40 },
    ],
  },
  {
    id: 'space-ikoyi-boardroom',
    title: 'The Glasshouse Executive Boardroom',
    tagline: 'C-Suite boardroom with 85" 4K presentation display & Polycom AV conferencing',
    description: 'Prestigious executive boardroom in upscale Ikoyi overlooking the waterfront. Features high-definition video conferencing, soundproofed acoustic walls, automatic electric blackout blinds, and white-glove beverage service for high-stakes investor pitches and director meetings.',
    category: 'meeting',
    city: 'Lagos',
    state: 'Lagos State',
    neighborhood: 'Ikoyi',
    address: '22 Bourdillon Road, Ikoyi, Lagos',
    latitude: 6.4474,
    longitude: 3.4356,
    pricePerHour: 18000,
    pricePerDay: 110000,
    capacity: 16,
    hasBackupPower: true,
    powerType: 'Dual Diesel Generators',
    powerUptimeGuaranteePercent: 100,
    internetSpeedMbps: 500,
    internetIsp: 'Liquid Intelligent Tech (Redundant)',
    noiseLevel: 'Silent / Library',
    images: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '85-inch 4K Sony Presentation Display',
      'Polycom Studio 4K Conference Cam',
      'Dual Acoustic Microphone Array',
      'High-Speed Internet (500Mbps)',
      '100% Uninterrupted Power',
      'Wireless Screen Mirroring (AirPlay/Miracast)',
      'Executive Whiteboard & Digital Flipchart',
      'Complimentary Nespresso & Gourmet Biscuits',
    ],
    rating: 5.0,
    reviewsCount: 64,
    host: {
      id: 'host-002',
      name: 'Emeka Nwosu',
      companyName: 'Bourdillon Executive Suites',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 809 112 3344',
      email: 'emeka@bourdillonsuites.ng',
      responseRatePercent: 100,
      responseTimeMinutes: 2,
      totalSpaces: 2,
      rating: 5.0,
    },
    operatingHours: {
      open: '08:00',
      close: '21:00',
      days: 'Mon - Sun',
    },
    rules: [
      'Professional attire required within building lobby',
      'AV support technician available on standby',
      'Catering must be coordinated with facility manager',
    ],
    tags: ['Boardroom', 'C-Suite', 'Ikoyi Waterfront', '4K Video AV'],
    isVerified: true,
    isSuperhost: true,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'available_today',
    nextAvailableSlot: {
      label: 'Today • 14:00',
      date: 'Today',
      time: '14:00',
    },
    occupancyLevel: 'busy',
  },
  {
    id: 'space-lekki-podcast',
    title: 'Soundwave Acoustic Podcast Suite',
    tagline: 'Professional 4-person podcast recording studio with Shure SM7B mics & Rodecaster Pro II',
    description: 'Fully calibrated broadcast studio in Lekki Phase 1 with multi-angle 4K Blackmagic cameras, custom RGB accent lighting, Rodecaster Pro II audio console, and soundproof treated walls (STC 65). Ideal for podcast hosts, voiceover artists, and digital content creators.',
    category: 'podcast',
    city: 'Lagos',
    state: 'Lagos State',
    neighborhood: 'Lekki Phase 1',
    address: 'Block 12, Admiralty Way, Lekki Phase 1, Lagos',
    latitude: 6.4478,
    longitude: 3.4723,
    pricePerHour: 15000,
    pricePerDay: 90000,
    capacity: 6,
    hasBackupPower: true,
    powerType: 'Solar + Inverter',
    powerUptimeGuaranteePercent: 100,
    internetSpeedMbps: 250,
    internetIsp: 'Spectranet Pure Gigabit',
    noiseLevel: 'Soundproofed Studio',
    images: [
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '4x Shure SM7B Dynamic Microphones',
      'Rodecaster Pro II Production Console',
      '2x Sony A7IV 4K Overhead & Cross Cams',
      'Soundproof Treated Vocal Booth',
      'Custom Neon & RGB Backlight Scenes',
      'Live Streaming Switcher & Cloud Uplink',
      'Dedicated Sound Engineer on site',
      'Instant Raw File Export on SD/USB 3.0',
    ],
    rating: 4.92,
    reviewsCount: 89,
    host: {
      id: 'host-003',
      name: 'Tobi Bakare',
      companyName: 'Soundwave Media Lagos',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 818 765 4321',
      email: 'tobi@soundwavemedia.ng',
      responseRatePercent: 98,
      responseTimeMinutes: 10,
      totalSpaces: 3,
      rating: 4.92,
    },
    operatingHours: {
      open: '09:00',
      close: '23:00',
      days: 'Mon - Sun',
    },
    rules: [
      'No drinks without lids inside recording booth',
      'Sound engineer is included for audio monitoring',
      'Arrive 10 minutes prior for microphone sound checks',
    ],
    tags: ['Podcast Studio', 'Shure SM7B', 'Soundproofed', 'Lekki'],
    isVerified: true,
    isSuperhost: true,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'available_now',
    occupancyLevel: 'low',
  },
  {
    id: 'space-yaba-incubator',
    title: 'Silicon Lagoon Developer Hub',
    tagline: '24-hour hacker space in the tech cradle of Yaba with high-speed internet & backup power',
    description: 'The premier developer sanctuary located in the heart of Yaba tech corridor. Built specifically for software engineers, blockchain devs, and early-stage startup squads who need reliable 24/7 power, high-speed internet, ergonomic desks, and endless black coffee.',
    category: 'coworking',
    city: 'Lagos',
    state: 'Lagos State',
    neighborhood: 'Yaba',
    address: '294 Herbert Macaulay Way, Yaba, Lagos',
    latitude: 6.5095,
    longitude: 3.3711,
    pricePerHour: 2200,
    pricePerDay: 12000,
    capacity: 60,
    hasBackupPower: true,
    powerType: 'Heavy Duty Gen + Solar Hybrid',
    powerUptimeGuaranteePercent: 99.8,
    internetSpeedMbps: 200,
    internetIsp: 'MainOne Dark Fiber',
    noiseLevel: 'Moderate / Focus Buzz',
    images: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '24/7 Redundant Generator & Solar Backup',
      '200Mbps High-Speed Internet',
      'Dual 27" 4K Monitors on Select Desks',
      'Whiteboard Brainstorming Walls',
      'Free Flowing Drip Coffee & Green Tea',
      'Quiet Nap & Meditation Pod',
      'Cat6 Wired Gigabit LAN',
      '24/7 Security & CCTV',
    ],
    rating: 4.85,
    reviewsCount: 215,
    host: {
      id: 'host-004',
      name: 'Chidi Okonkwo',
      companyName: 'Silicon Lagoon Labs',
      avatar: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 805 223 9988',
      email: 'chidi@siliconlagoon.ng',
      responseRatePercent: 97,
      responseTimeMinutes: 12,
      totalSpaces: 1,
      rating: 4.85,
    },
    operatingHours: {
      open: '24 Hours',
      close: '24 Hours',
      days: 'Mon - Sun (24/7 Access)',
    },
    rules: [
      'Respect the quiet zone after 22:00',
      'Clean monitors and desk surface after your sprint',
      'Guest passes limited to 2 hours in common area',
    ],
    tags: ['Yaba Tech', '24/7 Access', 'Developer Focused', 'Budget Friendly'],
    isVerified: true,
    isSuperhost: false,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'available_now',
    occupancyLevel: 'busy',
  },
  {
    id: 'space-abuja-maitama',
    title: 'Aso Rock Executive Business Lounge',
    tagline: 'Luxury private offices and diplomatic meeting facilities in Maitama, Abuja',
    description: 'Ultra-luxurious private suites and meeting salons in Maitama District, Abuja. Tailored for corporate directors, policy leaders, diplomats, and visiting executives. Features bulletproof glazed windows, marble interiors, private en-suite restrooms, and dedicated concierge.',
    category: 'private_office',
    city: 'Abuja',
    state: 'FCT',
    neighborhood: 'Maitama',
    address: '18 Gana Street, Maitama, Abuja',
    latitude: 9.0882,
    longitude: 7.4983,
    pricePerHour: 25000,
    pricePerDay: 160000,
    capacity: 12,
    hasBackupPower: true,
    powerType: 'Dual Diesel Generators',
    powerUptimeGuaranteePercent: 100,
    internetSpeedMbps: 400,
    internetIsp: 'Galaxy Backbone Enterprise Fiber',
    noiseLevel: 'Silent / Library',
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Private En-suite Bathroom & Shower',
      'Biometric Door Lock & Intercom',
      '400Mbps Dedicated Internet Line',
      '100% Zero-Downtime Power Supply',
      'Personal Butler & Beverage Concierge',
      'Italian Leather Executive Recliners',
      'Secure Underground Valet Parking',
      'Complimentary Airport Transfer Option',
    ],
    rating: 4.98,
    reviewsCount: 42,
    host: {
      id: 'host-005',
      name: 'Amina Bello',
      companyName: 'Aso Prestige Hospitality',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 809 999 8877',
      email: 'amina@asoprestige.ng',
      responseRatePercent: 100,
      responseTimeMinutes: 3,
      totalSpaces: 2,
      rating: 4.98,
    },
    operatingHours: {
      open: '07:30',
      close: '22:30',
      days: 'Mon - Sat',
    },
    rules: [
      'Valid government ID required at security gate',
      'Prior guest list registration encouraged',
      'Strict confidentiality protocol on premises',
    ],
    tags: ['Abuja Luxury', 'Maitama', 'Private Suite', 'High Security'],
    isVerified: true,
    isSuperhost: true,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'fully_booked_today',
    nextAvailableSlot: {
      label: 'Tomorrow • 09:00',
      date: 'Tomorrow',
      time: '09:00',
    },
    occupancyLevel: 'almost_full',
  },
  {
    id: 'space-ikeja-event',
    title: 'The Foundry Tech Auditorium & Event Hall',
    tagline: 'Modern 150-capacity auditorium for product launches, hackathons and tech keynotes',
    description: 'State-of-the-art keynote hall and exhibition pavilion in Ikeja GRA. Equipped with dual 200-inch LED video walls, motorized stage lighting, wireless handheld microphones, high-speed audience Wi-Fi, and an adjoining outdoor cocktail terrace.',
    category: 'event',
    city: 'Lagos',
    state: 'Lagos State',
    neighborhood: 'Ikeja GRA',
    address: '45 Isaac John Street, Ikeja GRA, Lagos',
    latitude: 6.5925,
    longitude: 3.3578,
    pricePerHour: 45000,
    pricePerDay: 280000,
    capacity: 150,
    hasBackupPower: true,
    powerType: 'Dual Diesel Generators',
    powerUptimeGuaranteePercent: 100,
    internetSpeedMbps: 500,
    internetIsp: 'MainOne 1Gbps Dedicated Event Link',
    noiseLevel: 'Collaborative',
    images: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      'Dual 200" P2.5 High-Definition LED Video Walls',
      'Line-Array Sound System with 4x Wireless Mics',
      'Stage Lighting & Live Streaming Rig',
      'High-Density Wi-Fi for 250+ Devices',
      '100% Uninterrupted Power (Dual 250kVA Gens)',
      'Green Room for Speakers & VIPs',
      'Outdoor Reception & Catering Terrace',
      'Secure Parking for 50 Vehicles',
    ],
    rating: 4.95,
    reviewsCount: 56,
    host: {
      id: 'host-006',
      name: 'Babajide Ogundipe',
      companyName: 'Foundry Events Nigeria',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 803 445 6677',
      email: 'jide@foundryevents.ng',
      responseRatePercent: 99,
      responseTimeMinutes: 15,
      totalSpaces: 2,
      rating: 4.95,
    },
    operatingHours: {
      open: '07:00',
      close: '23:00',
      days: 'Mon - Sun',
    },
    rules: [
      'Technical setup permitted 2 hours prior to scheduled event',
      'External caterers must register with venue operations',
      'Decibel levels adhere to Lagos EPA standards after 22:00',
    ],
    tags: ['Event Hall', '150 Capacity', 'LED Video Wall', 'Ikeja GRA'],
    isVerified: true,
    isSuperhost: true,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'opens_tomorrow',
    nextAvailableSlot: {
      label: 'Tomorrow • 08:30',
      date: 'Tomorrow',
      time: '08:30',
    },
  },
  {
    id: 'space-vi-photostudio',
    title: 'Lumina Infinity Cyclorama Studio',
    tagline: 'Commercial photography & video production studio with continuous lighting & infinity wall',
    description: 'Premier photo and film production suite in Victoria Island. Boasts a 6m x 5m seamless white cyclorama curved wall, Godox studio strobes, continuous Aputure LED film lights, motorized paper backdrops, styling dressing room with illuminated vanity mirrors, and client review lounge.',
    category: 'photography',
    city: 'Lagos',
    state: 'Lagos State',
    neighborhood: 'Victoria Island',
    address: '8 Adeola Odeku Street, Victoria Island, Lagos',
    latitude: 6.4312,
    longitude: 3.4156,
    pricePerHour: 20000,
    pricePerDay: 130000,
    capacity: 15,
    hasBackupPower: true,
    powerType: 'Heavy Duty Gen + Solar Hybrid',
    powerUptimeGuaranteePercent: 100,
    internetSpeedMbps: 200,
    internetIsp: 'FiberOne High Speed',
    noiseLevel: 'Soundproofed Studio',
    images: [
      'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&auto=format&fit=crop&q=80',
    ],
    featuredImage: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80',
    amenities: [
      '6m x 5m White Seamless Cyclorama Infinity Wall',
      'Godox AD600 Pro Strobes with Softboxes & Grids',
      'Aputure 300d II Continuous Video Lights with Lanterns',
      'Motorized Color Paper Backdrops (Black, Red, Green, Yellow)',
      'Stylist Dressing Room with Lighted Vanity Mirrors',
      'Garment Steamer & Heavy Duty Clothing Racks',
      'Tethering Station with 32" Color-Calibrated 4K Monitor',
      'Client Hospitality Lounge with Cold Refreshments',
    ],
    rating: 4.88,
    reviewsCount: 73,
    host: {
      id: 'host-007',
      name: 'Ngozi Eze',
      companyName: 'Lumina Visual Studios',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      phone: '+234 812 345 6700',
      email: 'ngozi@luminavisuals.ng',
      responseRatePercent: 96,
      responseTimeMinutes: 10,
      totalSpaces: 1,
      rating: 4.88,
    },
    operatingHours: {
      open: '08:00',
      close: '21:00',
      days: 'Mon - Sun',
    },
    rules: [
      'Shoe covers required when walking on fresh white cyclorama floor',
      'Repaint fee applies if cyclorama floor is heavily marked',
      'Studio assistant is available to assist with lighting setup',
    ],
    tags: ['Photo Studio', 'Cyclorama Wall', 'Aputure Lighting', 'Victoria Island'],
    isVerified: true,
    isSuperhost: false,
    instantBooking: true,
    freeCancellation: true,
    availabilityStatus: 'available_today',
    nextAvailableSlot: {
      label: 'Today • 16:00',
      date: 'Today',
      time: '16:00',
    },
    occupancyLevel: 'busy',
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    spaceId: 'space-vi-hive',
    userId: 'user-002',
    userName: 'Kolawole Daniel',
    userRole: 'Senior Frontend Engineer @ Mono',
    rating: 5,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 4.8,
    cleanlinessRating: 5,
    valueRating: 4.9,
    comment: 'The power stability here is rock solid. Even during heavy grid outages in VI, the solar-gen auto-switch happened seamlessly without dropping my video call with London. Internet speeds tested at 295Mbps. Espresso bar on the 2nd floor is a huge bonus.',
    visitDate: 'Visited 4 days ago • Hot Desk Full Day',
    helpfulCount: 18,
    isHelpfulByUser: false,
    verifiedAmenities: ['24/7 Power', 'Starlink 500Mbps', 'Espresso Bar', 'Herman Miller Chair'],
    photos: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-10T14:32:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-002',
    spaceId: 'space-vi-hive',
    userId: 'user-003',
    userName: 'Zainab Mohammed',
    userRole: 'Lead Product Designer @ Paystack',
    rating: 5,
    powerRating: 5,
    internetRating: 4.9,
    noiseRating: 5,
    cleanlinessRating: 5,
    valueRating: 4.8,
    comment: 'Herman Miller Aeron chairs are genuinely ergonomic for 10-hour sprint days. The acoustic phone booths are super quiet for user testing calls. Super clean restrooms and great coffee.',
    visitDate: 'Visited last week • Dedicated Desk',
    helpfulCount: 12,
    isHelpfulByUser: false,
    verifiedAmenities: ['Acoustic Phone Booth', 'Ergonomic Task Chairs', 'Espresso Bar'],
    photos: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-01-28T09:15:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-003',
    spaceId: 'space-vi-hive',
    userId: 'user-005',
    userName: 'Emeka Nwosu',
    userRole: 'Tech Founder & CTO',
    rating: 4.8,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 4.6,
    cleanlinessRating: 4.9,
    valueRating: 4.7,
    comment: 'Booked a hot desk for my distributed team sprint. The Starlink + MainOne fiber dual link is ridiculously fast (sub-10ms ping to AWS EU-West). Zero latency on pair programming sessions.',
    visitDate: 'Visited 2 weeks ago • Hot Desk Pass',
    helpfulCount: 9,
    isHelpfulByUser: false,
    verifiedAmenities: ['Dual Fiber + Starlink', 'Dual Genset', 'Free Parking'],
    createdAt: '2025-01-18T11:20:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-004',
    spaceId: 'space-ikoyi-boardroom',
    userId: 'user-004',
    userName: 'Dr. Segun Adeleke',
    userRole: 'Managing Partner, Ventures Capital',
    rating: 5,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 5,
    cleanlinessRating: 5,
    valueRating: 5,
    comment: 'Impeccable boardroom setup. Our international investors connected via Polycom 4K and commented on how crystal clear the audio was. The hospitality staff served fresh refreshments during the pitch session.',
    visitDate: 'Visited Feb 14, 2025 • Executive Boardroom (4 hrs)',
    helpfulCount: 15,
    isHelpfulByUser: false,
    verifiedAmenities: ['Polycom 4K Conferencing', 'Motorized Blackout Blinds', 'Executive Barista'],
    photos: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-14T16:00:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-005',
    spaceId: 'space-ikoyi-glass',
    userId: 'user-006',
    userName: 'Amina Bello',
    userRole: 'Country Director, Global NGO',
    rating: 5,
    powerRating: 5,
    internetRating: 4.8,
    noiseRating: 4.9,
    cleanlinessRating: 5,
    valueRating: 4.9,
    comment: 'Spectacular glass facade with panoramic views of Lagos lagoon. Natural daylight is amazing for productivity. Ultra secure with turnstile biometric entry.',
    visitDate: 'Visited 5 days ago • Executive Private Suite',
    helpfulCount: 11,
    isHelpfulByUser: false,
    verifiedAmenities: ['Lagoon View', '24/7 Security', 'Biometric QR Access'],
    photos: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-18T10:00:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-006',
    spaceId: 'space-lekki-podcast',
    userId: 'user-007',
    userName: 'Tariq Al-Hassan',
    userRole: 'Creator & Host, The Africa Tech Narrative',
    rating: 5,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 5,
    cleanlinessRating: 5,
    valueRating: 5,
    comment: 'The acoustic dampening here is broadcast studio grade (-60dB floor). Shure SM7B mics with Rodecaster Pro II made our 3-hour recording effortless. Highly recommend the on-site sound engineer!',
    visitDate: 'Visited 1 week ago • 3hr Recording Session',
    helpfulCount: 14,
    isHelpfulByUser: false,
    verifiedAmenities: ['Shure SM7B Mics', 'Rodecaster Pro II', 'Acoustic Soundproofing'],
    photos: [
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-08T18:30:00Z',
    verifiedBooking: true,
  }
];
